apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: acm-policy-controller-library
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/GoogleCloudPlatform/acm-policy-controller-library.git
    revision: HEAD
    branch: main
    dir: bundles
    auth: none
     