---
# Kustomize Feature List
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list

namespace: mccm-poc-wc-nginx
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml